# Generated by Django 3.2.4 on 2021-06-21 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_by',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
