# Generated by Django 3.2.4 on 2021-06-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Categories',
            field=models.ManyToManyField(related_name='books', to='books.Category'),
        ),
    ]
